### ISSUE TITLE
update client

### ISSUE THREAD

**Issue by TokkiHeikkila** [snoups/3xui-shop#4]
Недавно сам писал бота для телеграм.
При обновлении клиента в панели 3x-ui с помощью:
await api.client.update(client.id, client)
Получал ошибку что "id не верный".

Оказалось что там нужен uuid пользователя. Который не приходит в запросе:
client = await api.client.get_by_email(user_id)

Пришлось отдельно сохранять uuid в базе данных, чтобы потом подставить uuid вместо id.

Возможно вам это информация бесполезна и это я такой аутист, не мог понять целый час, почему у меня клиент не обновляется)))

user = await crud.get_user(user_id)
client.expiry_time = "new expiry time"
client.id = user.user_uuid
await api.client.update(client.id, client)

**Comment by snoups** [comment]
Знаю, спасибо.

**Comment by Goosegit11** [comment]
короче iwatkot зачем-то потёр discussions, я там расписывал как это решить, вкратце используй метод получения всего инбаунда и оттуда бери информацию о клиенте, там будет UUID 

inbound = get_inbound()

client = inbound[0]

uuid = client.uuid

типа так

**Comment by Goosegit11** [comment]
@snoups я вообще не понимаю как твоим ботом пользоваться

в .env мы указываем логин и пароль, но серваки всё равно надо добавлять через бота, тоесть если у тебя несколько серваков, то у них должен быть одинаковый логин и пароль, это странно.

ну я добавил сервак, кнопка пинг работает, показывает красный кружок, при попытке чёто сделать пишет сервер недоступен. и чё делать
